---
name: "Distribute a helm image"
description: |
  This action copies a helm image to multiple registries.
author: martoc
inputs:
  source_registry:
    description: "Source registry"
    required: true
  source_workload_identity_provider:
    description: "Workload Identity Provider"
    required: false
  source_service_account:
    description: "Service Account"
    required: false
  source_region:
    description: |
      Region to push the helm to.
      Valid values: Google Cloud.
    required: false
  source_gcp_project_id:
    description: "Google Cloud Project ID"
    required: false
    default: ""
  target_registry:
    description: "Target registry"
    required: true
  target_workload_identity_provider:
    description: "Workload Identity Provider"
    required: false
  target_service_account:
    description: "Service Account"
    required: false
  target_region:
    description: |
      Region to push the container to.
      Valid values: Google Cloud or AWS regions.
    required: false
  target_gcp_project_id:
    description: "Google Cloud Project ID"
    required: false
  chart_name:
    description: "Helm chart in the format namespace/chart"
    required: true
  chart_version:
    description: "Helm chart chart_name"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        chart_name: 499.0.0
      if: ${{ inputs.source_registry == 'gcp' || inputs.target_registry == 'gcp' }}
    - uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.source_workload_identity_provider }}
        service_account: ${{ inputs.source_service_account }}
      if: ${{ inputs.source_registry == 'gcp' }}
    - name: Pull image from source
      shell: bash
      run: |
        gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin https://${{ inputs.source_region }}-docker.pkg.dev
        helm pull oci://${{ inputs.source_region }}-docker.pkg.dev/${{ inputs.source_gcp_project_id }}/${{ inputs.chart_name }} --version "${{ inputs.chart_version }}"
      if: ${{ inputs.source_registry == 'gcp' }}
    - uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.target_workload_identity_provider }}
        service_account: ${{ inputs.target_service_account }}
      if: ${{ inputs.target_registry == 'gcp' }}
    - name: Push image to target
      shell: bash
      run: |
        gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin https://${{ inputs.target_region }}-docker.pkg.dev
        helm push $(basename ${{ inputs.chart_name }}-${{ inputs.chart_version }}.tar.gz) oci://${{ inputs.target_region }}-docker.pkg.dev/${{ inputs.target_gcp_project_id }}/${{ inputs.chart_name }}
      if: ${{ inputs.target_registry == 'gcp' }}
